"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Navigation */}
      <nav className="border-b border-border bg-card">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <img src="/PubWize.png" alt="Pubwize" className="h-12" />
          </Link>
          <Link href="/" className="flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold font-display mb-4 text-foreground">Terms of Service</h1>
        <p className="text-sm mb-12 text-muted-foreground">Last updated: March 21, 2026</p>

        <div className="space-y-8 max-w-none">
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using Pubwize (operated by DraftRapid) ("we," "our," "us"), you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">2. Use License</h2>
            <p className="text-muted-foreground leading-relaxed">
              Permission is granted to use our web-based platform temporarily for personal or commercial content creation. This is the grant of a limited, non-exclusive, non-transferable license, not a transfer of title.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">3. Content Ownership and Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain all rights to the content you generate, refine, and publish using Pubwize. We do not claim ownership of your output. However, because content is generated by artificial intelligence models, it is provided "as-is". You are entirely responsible for reviewing, fact-checking, and ensuring the legality and accuracy of any AI-generated content prior to publication.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">4. Fair Use Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              To ensure high availability and prevent abuse of our AI models, unlimited and automated usage is subject to fair use limits. Use of automated scripts, bots, or any method to bypass our usage limits or artificially inflate API requests to GenAI models is strictly prohibited and may result in immediate termination of the account without refund.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">5. Merchant of Record, Billing & Subscriptions</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle provides all customer service inquiries and handles returns.
            </p>
            <p className="mt-3 text-muted-foreground leading-relaxed">
              Subscriptions auto-renew monthly or annually based on your selection.
            </p>
            <p className="mt-3 text-muted-foreground leading-relaxed">
              We offer a <strong>14-day money-back guarantee</strong> for new initial subscription purchases. Please refer to our{" "}
              <Link href="/refunds" className="underline text-gold hover:text-gold/80">
                Refund Policy
              </Link>{" "}
              for specifics.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">6. Prohibited Acts</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use the service to:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-muted-foreground mt-2">
              <li>Generate illegal, harmful, defamatory, or malicious content.</li>
              <li>Infringe on the intellectual property of third parties.</li>
              <li>Distribute malware or spam networks.</li>
              <li>Scrape, reverse-engineer, or attempt to extract the service's source code or proprietary GenAI prompts.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              In no event shall Pubwize or its suppliers/partners be liable for any indirect, incidental, special, consequential, or punitive damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the service, even if notified orally or in writing of the possibility of such damage.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">8. Governing Law & Jurisdiction</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms and your use of the service shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without giving effect to any principles of conflicts of law. Any disputes relating to the purchase or processing of payments shall be subject to terms specified by our Merchant of Record, Paddle.com.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">9. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              For queries related to your account or these terms, please reach out to:
            </p>
            <div className="mt-4 p-4 rounded-lg border border-border bg-card text-muted-foreground">
              <p><strong>Email:</strong> <a href="mailto:legal@pubwize.com" className="text-gold hover:underline">legal@pubwize.com</a></p>
              <p className="mt-2"><strong>Corporate Address:</strong><br />
                Pubwize<br />
                488 Zone E Kalengwa South<br />
                Kalulushi, Copperbelt 10101<br />
                Zambia</p>
            </div>
            <p className="mt-4 text-muted-foreground leading-relaxed">
              For payment or billing queries, please contact Paddle support at{" "}
              <a href="https://paddle.net" target="_blank" rel="noopener noreferrer" className="text-gold hover:underline">paddle.net</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
